<?php
// 3.0.0- txtTLDdev
//

$langues = array(
	'langue' => 'Español',
	'locale' => 'Argentina',
	'titreHtml' => 'WAMPSERVER Inicio',
	'titreConf' => 'Configuracion del servidor',
	'versa' => 'Version de Apache:',
	'doca2.2' => 'httpd.apache.org/docs/2.2/es/',
	'doca2.4' => 'httpd.apache.org/docs/2.4/es/',
	'versp' => 'Version de PHP:',
	'server' => 'Software en Servidor:',
	'documentation' => 'Documentacion',
	'docp' => 'www.php.net/manual/es/',
	'versm' => 'Version de MySQL:',
	'docm' => 'dev.mysql.com/doc/index.html',
	'versmaria' => 'Version de MariaDB: ',
	'docmaria' => 'mariadb.com/kb/en/mariadb/documentation',
	'phpExt' => 'Extensiones cargadas: ',
	'titrePage' => 'Herramientas',
	'txtProjet' => 'Sus proyectos',
	'txtNoProjet' => 'No hay proyectos todavia.<br />Para crear uno nuevo, simplemente crea un directorio en \'www\'.',
	'txtAlias' => 'Sus alias',
	'txtNoAlias' => 'No hay alias todavía.<br />Para crear uno nuevo, usa el menú WAMPSERVER.',
	'txtVhost' => 'Tu VirtualHost',
	'txtServerName' => 'El ServerName %s tiene un error de sintaxis en el archivo %s',
	'txtDocRoot' => 'El ServerName %s usa DocumentRoot %s reservado para localhost',
	'txtTLDdev' => 'El ServerName %s usa TLD %s que es monopolizado por los navegadores web. Usar otro TLD (.prueba por ejemplo)',
	'txtServerNameIp' => 'IP %s para Servername %s no es valido en el archivo %s',
	'txtVhostNotClean' => 'El archivo %s no ha sido limpiado. Quedan ejemplos de VirtualHost como: dummy-host.example.com',
	'txtNoVhost' => 'Sin VirtualHost todavía. Agregue uno para cada proyecto en el archivo: wamp/bin/apache/apache%s/conf/extra/httpd-vhosts.conf',
	'txtNoIncVhost' => 'Descomentar o añadir <i>Incluir conf/extra/httpd-vhosts.conf</i> en archivo wamp/bin/apache/apache%s/conf/httpd.conf',
	'txtNoVhostFile' => 'El archivo: %s no existe',
	'txtNoPath' => 'El path %s para %s no existe (Archivo %s)',
	'txtNotWritable' => 'El archivo: %s no tiene permiso de escritura',
	'txtNbNotEqual' => 'El numero de %s no coincide con el número de %s en el archivo %s ',
	'txtAddVhost' => 'A&ntilde;adir un host virtual',
	'txtPortNumber' => 'El número de puerto para %s  no tiene el valor correcto o no es el mismo en el archivo %s',
	'txtCorrected' => 'Algunos errores de VirtualHosts pueden ser corregidos.',
	'forum' => 'Foro de Wampserver',
	'forumLink' => 'http://forum.wampserver.com/list.php?2',
	'portUsed' => 'Puerto definido para Apache: ',
	'mysqlportUsed' => 'Puerto definido para MySQL: ',
	'mariaportUsed' => 'Puerto definido para MariaDB: ',
	'nolocalhost' => 'Es una mala idea agregar localhost en la url de proyectos de lanzamiento. Lo mejor es definir VirtualHost en el archivo <br />wamp/bin/apache/apache%s/conf/extra/httpd-vhosts.conf<br /> y no agregar localhost en la url.',
	);
?>
